### ISSUE TITLE
The rendering is flickering when we are moving a blueprint actor in editor

### ISSUE THREAD

**Issue by luofxgucas** [KoderzUnreal/RuntimeMeshComponent#182]
Version： RMC 4.1/UE 4.24/VS2017

I used the your recommended example that you give: https://github.com/KoderzUnreal/RuntimeMeshComponent-Examples.
And I tested BasicPMCStyleRMC Actor

1.  I dragged a C++ BasicPMCStyleRMC Actor into the scene in the editor. When i was moving this actor use my mouse, the rendering of this actor look normally.
2. I created a BP Actor for this C++ actor. I dragged this actor into the scene in the editor. When I was moving this BP Actor, the rendering of this actor is flickering.

Why does this happend?

**Comment by luofxgucas** [comment]
I found this bug is caused by the OnConstruct function. It's not suitable to put many logic in OnConstruct because it is called frequently in editor. More reference: https://isaratech.com/ue4-be-careful-with-the-construction-script/

**Comment by Koderz** [comment]
This is basically just how construction scripts work in UE4. I don't recommend them for very heavy logic, but the reason some of those flicker is it's running the construction script over and over while you drag it so it's just a delay in getting from restarting the actor to having all the mesh data in GPU rendering. 

It's not really a bug, you should only ever see that in editor. Construction runs only in editor for things place in editor and runs exactly once on spawn for an actor spawned in game so there's really no harm in this. I just strongly suggest against putting heavy generation logic directly in the construction script. 

Also threaded providers can run a couple frames behind so that'd cause this type behavior too since that's non-deterministic.

If there's some specific reason this is hindering you though I'd be interested in that and more then open to help find a solution.

Let me know if you have any other issues or questions!
-Chris
